// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU5gUPQUArc1C_08CAec2PQyIE6jWG_I8',
    appId: '1:328099966286:web:481ef8b70787a32ed6021f',
    messagingSenderId: '328099966286',
    projectId: 'garage-pro-d63ae',
    authDomain: 'garage-pro-d63ae.firebaseapp.com',
    storageBucket: 'garage-pro-d63ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB543ReKbyg0Ai-gVFC18ivylZz70ZdKFA',
    appId: '1:328099966286:android:8d6b244960be43d5d6021f',
    messagingSenderId: '328099966286',
    projectId: 'garage-pro-d63ae',
    storageBucket: 'garage-pro-d63ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlAAekySwAqNqRmJowRnJhR5NCLm1zidM',
    appId: '1:328099966286:ios:6ab1c1f3d0361fd0d6021f',
    messagingSenderId: '328099966286',
    projectId: 'garage-pro-d63ae',
    storageBucket: 'garage-pro-d63ae.firebasestorage.app',
    iosBundleId: 'com.AhmedRamadan.garagePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlAAekySwAqNqRmJowRnJhR5NCLm1zidM',
    appId: '1:328099966286:ios:6ab1c1f3d0361fd0d6021f',
    messagingSenderId: '328099966286',
    projectId: 'garage-pro-d63ae',
    storageBucket: 'garage-pro-d63ae.firebasestorage.app',
    iosBundleId: 'com.AhmedRamadan.garagePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU5gUPQUArc1C_08CAec2PQyIE6jWG_I8',
    appId: '1:328099966286:web:ee99997cc1d35305d6021f',
    messagingSenderId: '328099966286',
    projectId: 'garage-pro-d63ae',
    authDomain: 'garage-pro-d63ae.firebaseapp.com',
    storageBucket: 'garage-pro-d63ae.firebasestorage.app',
  );
}
